-- Persisted quote images generated by the creative tool (history gallery)
CREATE TABLE IF NOT EXISTS creative_images (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quote TEXT NOT NULL,
  prompt TEXT NULL,
  tone VARCHAR(50) NOT NULL DEFAULT 'professional',
  -- Where the bytes live: 'local' today, 's3' once remote storage is enabled.
  storage_driver VARCHAR(20) NOT NULL DEFAULT 'local',
  -- Driver-relative key (e.g. "3/abc123.png"), never an absolute path.
  storage_key VARCHAR(500) NOT NULL,
  url VARCHAR(500) NOT NULL,
  width INTEGER NOT NULL,
  height INTEGER NOT NULL,
  bytes INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_creative_images_user_created
  ON creative_images (user_id, created_at DESC);
